[server] ##nomal type
mode = "dev"
### [코드리뷰] 
# 위의 mode 에는 dev라는 string 값이 세팅이 되어 있어 
# 해당 config가 dev용임을 쉽게 확인할 수 있는 좋은 코드입니다.
# 그러나 human error를 방식하기 위해, 개발과 운영환경의 값이 다른 데이터들은 
# 해당 값을 시스템 변수나, 환경변수로 세팅해둔다면, 개발환경과, 운영환경의 config를 실수로 잘못 갈아끼웠을 때,
# 발생하는 장애들을 예방할 수 있을 것입니다.
###
port = ":8080"

[db] #data access object
[db.user] #이중 map type map[string]map[string]interface{}
host = "mongodb://localhost:27017"
user = "user"
pass = "user!@"
name = "userDB"

[db.account]
host = "mongodb://localhost:27017"
user = "admin"
pass = "admin!@"
name = "accountDB"

#worker pool job object
[[work]] #배열구조, jobs []job
name = "HeartBeat"
desc = "log"
excute = "x"
duration = 300
args = "resv"

[[work]]
name = "exam"
desc = "exam"
excute = "x"
duration = 60
args = "exam"

[log]
level = "debug" # debug or info
fpath = "./logs/go-loger" # 로그가 생성될 경로 : ./logs, 로그파일명 go-loger_xxx.log
msize = 2000    # 2g : megabytes
mage = 7        # 7days
mbackup = 5    # number of log files
